blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/contentful/contentful-sdk-jsdoc/discussions
    about: Ask questions or discuss ideas with the community
  - name: Documentation
    url: https://contentful.com/docs
    about: Check out our documentation for help and guides
  - name: Security Vulnerability
    url: https://github.com/contentful/contentful-sdk-jsdoc/security/advisories/new
    about: Report a security vulnerability privately
